/// Flutter icons Main
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Main
///      fonts:
///       - asset: fonts/Main.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Main {
  Main._();

  static const _kFontFam = 'Main';
  static const String? _kFontPkg = null;

  static const IconData shirt_solid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utensils_solid = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_solid = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_solid = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_solid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
